### ISSUE TITLE
Automate tracking of the community pull requests

### ISSUE THREAD

**Issue by MisRob** [learningequality/test-actions#21]
## Background

Almost every morning, @MisRob will make a cup of :tea:, and opens the list of [Kolibri pull requests](https://github.com/learningequality/kolibri/pulls), [Studio pull requests](https://github.com/learningequality/studio/pulls), and [KDS pull requests](https://github.com/learningequality/kolibri-design-system/pulls) and finds all new/updated/closed pull requests authored by external volunteers.

Then she logs them in Google Sheet spreadsheet saved on Learning Equality's Google Drive.

![Screenshot from 2024-08-11 20-07-14](https://github.com/user-attachments/assets/c41b0e2d-21a6-403e-b629-f392757c03a9)

The spreadsheet is used for multiple purposes, for example to pull out user names of contributors for a particular month so we can send them gratitudes, to nudge core team members to follow-up on reviews, to have an overall overview of activity, etc. 

## Summary

The goal of this task is to automate the aforementioned workflow. This will help us save some time that could be used for interacting with the community instead, and will also prevent from missing some pull requests.

On a high-level it would work:
- A new row is inserted to the spreadsheet when a new pull request is open in Kolibri, Studio, and KDS repositories by an author who's not a member of Learning Equality GitHub organization
- An existing row is updated when a corresponding pull request is updated (merged, closed, title changed, reviewer changed, assignee changed...)

Spreadsheet columns:

- Merged: date when a PR was merged, in `yyyy-mm-dd format`, example  `2024-03-25`
- Link: PR link, example `https://github.com/learningequality/kolibri/pull/12382`
- Author: Author's GitHub username, example `MisRob`
- Title: PR title, example `Add initial version of Bloom Renderer`
- Repository: Repository name, example `kolibri-design-system`
- Updated: Date when a spreadsheet row was updated the last time, in `yyyy-mm-dd format`, example  `2024-03-25`
- Reviewers: GitHub usernames of "Reviewers", separated by comma, example `rtibbles,akolson,MisRob`
- Assignees: GitHub usernames of "Assignees", separated by comma, example `rtibbles,akolson,MisRob`

All information above should be updated in the spreadsheet whenever there is a related change on a pull request.

The update in the PR should never replace the whole sheet row. Rather, it needs to only update the corresponding column in the row (this is because there will be some manually added columns at the end of rows that shouldn't be disappearing)

## Guidance

- For the first version, it may be best to start two test repositories and a new Google Sheet. As soon as the implementation is stable, we will move to Learning Equality repositories and configure the action with access tokens.
- For complex tasks, it is rather hard for our team to maintain shell-based implementations so
  - Using Python or JavaScript whenever possible is recommended. Here's some good guidance from @rtibbles https://github.com/learningequality/kolibri-design-system/pull/547#issuecomment-2083044718.
  - Please pay attention to readability and maintainability of implementation (to allow GH actions newbie such as @MisRob to add a new spreadsheet column with a bit of study in a reasonable time frame :)
- As per @rtibbles's guidance, whenever possible we try to avoid 3rd party actions, except the official ones (security and upgrade related issues)
- It'd be welcome if we didn't need to have three copies of the same action in aforementioned repositories, and also adding a new repository would be ideally straightforward

## Comments

Not necessary but if it'd be interesting, we'd welcome exploration of implementing a layer that we could use as a basis for common tasks for many actions. For example, it could have a form of a file with helper functions `get_pull_request_author`, `get_pull_request_title`, `is_member_of_le`, etc. Perhaps this task could lay down some foundations.

**Comment by GarvitSinghal47** [comment]
@MisRob Could you please assign this issue to me? 😄

**Comment by MisRob** [comment]
Yes , thank you @GarvitSinghal47

**Comment by MisRob** [comment]
This is now done and will be observed in production. Thanks so much @GarvitSinghal47, this is incredibly helpful for me.
